config/routes.rb
Rails.application.routes.draw do
  root 'toppages#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :task_lists, only: [:index, :show, :create, :update, :destroy]

  resources :users, only: [:show, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task_list.rb
class TaskList < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true
  validates :status, length: {maximum: 10}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :task_lists
  
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                  uniqueness: { case_sensitive: false }
  
  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]

    if login(email, password)
      flash[:success] = "ログインに成功しました！"
      redirect_to @user
    else
      flash.now[:danger] = "ログインに失敗しました！"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :create, :update]
  
  def index
    @tasklists = TaskList.all
  end
  
  def show
    @tasklist = TaskList.find(params[:id])
    
    @tasklists = TaskList.new
    
    @list_name = User.find_by(id: @tasklist.user_id)
  end
  
  def create
    @tasklist = current_user.task_lists.build(tasklist_params)
    
    if @tasklist.save
      flash[:success] = "作成したからには達成しましょうね！"
      redirect_to "/users/#{session[:user_id]}"
    else
      @tasklists = current_user.task_lists.build
      @user = User.find_by(id: session[:user_id])
      @mylists = current_user.task_lists.where(user_id: session[:user_id])
      
      flash.now[:danger] = 'タスクの作成に失敗したようです。'
      render :template => "users/show"
    end
  end

  def update
    @tasklist = TaskList.find(params[:id])
    
    if @tasklist.update(tasklist_params)
      redirect_to "/users/#{session[:user_id]}"
    else
      render :show
    end
  end
  
  def destroy
    @tasklist = TaskList.find(params[:id])
    @tasklist.destroy
    
    redirect_to "/users/#{session[:user_id]}"
  end
  
  private
  
  def tasklist_params
    params.require(:task_list).permit(:content, :status)
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @tasklists = TaskList.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  def show
    @user = User.find_by(id: params[:id])
    
    @mylists = TaskList.where(user_id: params[:id])
    
    @tasklists = TaskList.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "登録が完了しました！"
      redirect_to @user
    else
      flash.now[:danger] = "登録失敗・・再度登録願います！"
      render :new
    end
  end

  def destroy
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class ="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>    
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale = 1">

    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel ="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <header>
      <nav class ="navbar navbar-default">
        <div class ="container-fluid">
          <div class="navbar-header">
            <button type ="button" class="navbar-toggle collapsed" data-toggle ="collapse" data-target="#navbarEexample1">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class ="collapse navbar-collapse" id ="navbarEexample1">
              <ul class ="nav navbar-nav">
                <% if logged_in? %>
                  <li><%= link_to 'みんなのタスク一覧', task_lists_path %></li>
                  <li><%= link_to 'マイタスク', "/users/#{session[:user_id]}" %></li>
                  <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to 'HOME', root_path %></li>
                  <li><%= link_to 'ユーザー登録', new_user_path %></li>
                  <li><%= link_to 'ログイン', login_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </nav>
      <% flash.each do |message_type, message| %>
        <div class ="alert alert-<%= message_type %> text-center"><%= message %></div>
      <% end %>
    </header>
      <%= yield %>
  </body>
</html>

app/views/task_lists/index.html.erb
<!-- トップページ -->
<div class="row">
  <div class="col-sm-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    <h1 class ="h1">みんなのタスク</h1>
    <br>
    <h3>みんなのタスクを参考に自分のタスクを作成しよう！</h3>
    <p class ="show-container">みんなのタスクを見ることで普段気づかないタスクが見つかるかも？</p>
    <br>
    <ul>
    <% @tasklists.each do |tasklist| %>
      <li class ="taskshow_li"><%= link_to tasklist.content, task_list_path(tasklist) %> : <%= link_to tasklist.user.name, user_path(tasklist.user.id) %></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/task_lists/show.html.erb
<h1>Task Details</h1>
<h3><%= @list_name.name %>さんタスク</h3>

<div class ="jumbotron">
  <div class ="container">
    <p class ="taskshow_li tasklink_color">タスク : <%= @tasklist.content %></p><br>
    <p class ="taskshow_li tasklink_color">メモ :  <%= @tasklist.status %></p><br>
    <% if current_user == @list_name %> 
      <div class ="form_container">
    		<%= form_for(@tasklist) do |f| %>
    			<div class ="imput-group">
    				<%= f.label :content, 'Myタスクの編集' %>
    				<%= f.text_field :content, class: 'form-control' %>
    			</div>
    			<div class ="imput-group">
    				<%= f.label :status, 'メモ' %>
    				<%= f.text_field :status, class: 'form-control' %>
    			</div>
    			<br>
    			<%= f.submit 'タスクを編集', class: 'btn btn-primary' %>
    		<% end %>
    	</div>
  		<div class ="destroy_margin"></div>
    	<%= link_to 'タスクの削除', @tasklist, method: :delete, data: { confirm: '本当によろしいですか！？' }, class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/toppages/index.html.erb
<div class="row">
  <div class="col-sm-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    <h1 class ="h1">タスクリスト</h1>
    <br>
    <h3>タスクを共有しよう！</h3>
    <p class ="show-container">タスクを共有し優先事項を整理しましょう！</p>
    <br>
    <ul>
    <% @tasklists.each do |tasklist| %>
      <li class ="taskshow_li"><%= link_to tasklist.content, task_list_path(tasklist), class: 'tasklink_color' %></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/users/new.html.erb
<h1>新規登録</h1>
<div class="row">
	<div class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
		<%= form_for(@user) do |f| %>
			<div class ="imput-group">
				<%= f.label :name, '名前' %>
				<%= f.text_field :name, class: 'form-control' %>
			</div>
			<div class ="imput-group">
				<%= f.label :emai, 'メールアドレス' %>
				<%= f.email_field :email, class: 'form-control' %>
			</div>
			<div class ="imput-group">
				<%= f.label :password, 'パスワード' %>
				<%= f.password_field :password, class: 'form-control' %>
			</div>
			<div class ="imput-group">
				<%= f.label :password_confirmation, 'パスワードの確認' %>
				<%= f.password_field :password_confirmation, class: 'form-control' %>
			</div>
			<br>
			<%= f.submit '保存', class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>さんのタスクリスト</h1>


<div class="row">
  <% if current_user == @user %>
  	<div class="pull-right col-xs-10 col-xs-pull-1 col-sm-5 col-sm-pull-1 col-lg-4 col-lg-pull-2">
  		<%= form_for(@tasklists) do |f| %>
  			<div class ="imput-group">
  				<%= f.label :content, 'Myタスク作成' %>
  				<%= f.text_field :content, class: 'form-control' %>
  			</div>
  			<div class ="imput-group">
  				<%= f.label :status, 'メモ' %>
  				<%= f.text_field :status, class: 'form-control' %>
  			</div>
  			<br>
  			<%= f.submit '保存', class: 'btn btn-primary' %>
  		<% end %>
  	</div>
    <div class ="pull-left col-xs-9 col-xs-push-1 col-sm-5 col-sm-push-1 col-lg-4 col-lg-push-2">
      <ul>
        <% @mylists.each do |mylist| %>
          <br>
          <li class ="taskshow_li"><%= link_to mylist.content, "/task_lists/#{mylist.id}", class: "tasklink_color" %></li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <div class ="col-sm-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
      <ul>
        <% @mylists.each do |mylist| %>
          <br>
          <li class ="taskshow_li"><%= link_to mylist.content, "/task_lists/#{mylist.id}", class: "tasklink_color" %></li>
        <% end %>
      </ul>
    </div> 
  <% end %>
</div>